spring:
  application:
    name: firstSpringBoot
  datasource:
      url: jdbc:mysql://localhost:3306/mystore?createDatabaseIfNotExist=true
      username: root
      password: password
  jpa:
    show-sql: true

#Password changed to 'password' on local branch after reinstalling MySQL; previously default was P@ssword; update if needed